import esphome.codegen as cg

goodhome_ns = cg.esphome_ns.namespace("goodhome")

CONF_MULTIPLIER = "multiplier"
CONF_ANTIF_TEMPERATURE = "antifreeze_temperature"
CONF_ECO_TEMPERATURE = "eco_temperature"
CONF_COMF_TEMPERATURE = "comfort_temperature"
CONF_OVERRIDE_TEMPERATURE = "override_temperature"
CONF_TARGET_TEMPERATURE = "target_temperature"
CONF_CTN_ADJUST = "ctn_ajust"
CONF_WINDOW_TIMEOUT = "open_window_timeout"
CONF_LANGUAGE = "language"
CONF_TARGET_MODE = "target_mode"
CONF_OPEN_WINDOW = "open_window_detection"
CONF_SELF_LEARNING = "self_learning"
CONF_MANUAL_MODE = "manual_mode"
CONF_PRESENCE_SENSOR = "presence_sensor"
CONF_LEARNING_IMPROVE = "self_learning_improve"
CONF_DAYLIGHT_SAVING = "daylight_saving"
CONF_ROOM_TYPE = "room_type"
CONF_ROOM_NAME = "room_name"
CONF_HARDWARE_VERSION = "hardware_version"
CONF_FIRMWARE_VERSION = "firmware_version"
CONF_CODE_NAME = "code_name"
CONF_DUTY_CYCLE = "duty_cycle"
CONF_LONG_ABSENCE_TIMEOUT = "long_absence_timeout"
CONF_SHORT_ABSENCE_TIMEOUT = "short_absence_timeout"
CONF_LOCAL_TIME = "local_time"
CONF_SELF_LEARNING_COUNT = "self_learning_count"
CONF_FAULT_COUNTER = "fault_counter"
CONF_RESTART_COUNTER = "restart_counter"

UNIT_DAY = "day"